DROP TABLE IF EXISTS pokemon;

CREATE TABLE pokemon (
	abilities varchar(100),
	against_bug DECIMAL(2,1),
	against_dark DECIMAL(2,1),
	against_dragon DECIMAL(2,1),
	against_electric DECIMAL(2,1),
	against_fairy DECIMAL(2,1),
	against_fight DECIMAL(2,1),
	against_fire DECIMAL(2,1),
	against_flying DECIMAL(2,1),
	against_ghost DECIMAL(2,1),
	against_grass DECIMAL(2,1),
	against_ground DECIMAL(2,1),
	against_ice DECIMAL(2,1),
	against_normal DECIMAL(2,1),
	against_poison DECIMAL(2,1),
	against_psychic DECIMAL(2,1),
	against_rock DECIMAL(2,1),
	against_steel DECIMAL(2,1),
	against_water DECIMAL(2,1),
	attack INTEGER,
	classification varchar(100),
	defense INTEGER,
	height DECIMAL(5,2),
	hp INTEGER,
	name varchar(50),
	number INTEGER PRIMARY KEY,
	sp_attack INTEGER,
	sp_defense INTEGER,
	speed INTEGER,
	type_one varchar(50),
	type_two varchar(50),
	weight DECIMAL (7,2),
	generation INTEGER,
	legendary BOOLEAN
);